import React from 'react';
import Layout from '@theme/Layout';
import '../../css/mathematics.css';
import { BlockMath, InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css';

export default function QuaternionAttitudeController() {
  return (
    <Layout
      title="SDF – Quaternion Attitude Controller"
      description="Mathematical formulation and telemetry-based verification of quaternion attitude stabilization and angular-rate damping in the Spaceflight Dynamics Framework"
    >
      <main className="mathContainer">

        <h1>Quaternion Attitude Controller</h1>

        <section className="mathSection">
          <h2>1. Model Overview</h2>

          <p>
            The SDF attitude-control model provides two complementary rotational
            control modes for a spacecraft equipped with reaction-control-system
            thrusters:
          </p>

          <ul>
            <li>
              <strong>Kill Rotation</strong> damps the spacecraft body angular
              velocity toward zero without prescribing an absolute target attitude.
            </li>
            <li>
              <strong>Stabilize</strong> captures the spacecraft attitude at
              activation and subsequently drives the vehicle back toward this
              reference attitude while simultaneously damping angular motion.
            </li>
          </ul>

          <p>
            The attitude-hold formulation operates directly in quaternion space.
            Euler-angle conversion is therefore not required inside the control
            model, avoiding the singularities associated with three-angle attitude
            parameterizations.
          </p>

          <p>
            The controller output is interpreted as a three-axis rotational
            command. The physical torque acting on the spacecraft is generated by
            the separate RCS actuator and control-allocation models.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>2. Quaternion Attitude Representation</h2>

          <p>
            Spacecraft orientation is represented by the normalized quaternion
          </p>

          <BlockMath
            math={`
              q
              =
              \begin{bmatrix}
              q_w \\
              q_x \\
              q_y \\
              q_z
              \end{bmatrix},
              \qquad
              \lVert q \rVert = 1
            `}
          />

          <p>
            with scalar component <InlineMath math={'q_w'} /> and vector component
          </p>

          <BlockMath
            math={`
              \mathbf{q}_v
              =
              \begin{bmatrix}
              q_x \\
              q_y \\
              q_z
              \end{bmatrix}.
            `}
          />

          <p>
            Because the quaternions <InlineMath math={'q'} /> and
            <InlineMath math={'-q'} /> describe the same physical orientation,
            the attitude-control formulation explicitly resolves this sign
            ambiguity when evaluating the rotational error.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>3. Quaternion Attitude Error</h2>

          <p>
            In Stabilize mode, the current attitude at the activation instant is
            stored as the reference attitude:
          </p>

          <BlockMath
            math={`
              q_{target}
              =
              q\left(t_{activation}\right)
            `}
          />

          <p>
            The attitude error is then formed as
          </p>

          <BlockMath
            math={`
              q_e
              =
              q_{target}^{-1}
              \otimes
              q_{current}
            `}
          />

          <p>
            where <InlineMath math={'\otimes'} /> denotes quaternion
            multiplication. For a unit quaternion,
            <InlineMath math={'q^{-1}=q^*'} />, so the inverse corresponds to the
            quaternion conjugate.
          </p>

          <p>
            To enforce the shortest rotational representation, the sign of the
            error quaternion is selected such that
          </p>

          <BlockMath
            math={`
              q_{e,w} \ge 0.
            `}
          />

          <p>
            If <InlineMath math={'q_{e,w}<0'} />, all quaternion coefficients are
            multiplied by <InlineMath math={'-1'} />. The proportional attitude
            error used by the controller is the vector part
          </p>

          <BlockMath
            math={`
              \mathbf{e}_q
              =
              \begin{bmatrix}
              q_{e,x} \\
              q_{e,y} \\
              q_{e,z}
              \end{bmatrix}.
            `}
          />
        </section>

        <hr />

        <section className="mathSection">
          <h2>4. Kill Rotation</h2>

          <p>
            Kill Rotation is a pure angular-rate damping mode. Its control
            objective is
          </p>

          <BlockMath math={'\boldsymbol{\omega} \rightarrow \mathbf{0}'} />

          <p>
            where <InlineMath math={'\boldsymbol{\omega}'} /> is the spacecraft
            angular velocity expressed in the spacecraft body-fixed frame.
            The three axes are treated independently according to
          </p>

          <BlockMath
            math={`
              \mathbf{u}_{KR}
              =
              -\mathbf{K}_{\omega}
              \odot
              \boldsymbol{\omega}
            `}
          />

          <p>
            with component-wise multiplication
            <InlineMath math={'\odot'} />. A small angular-rate deadband avoids
            unnecessary RCS commands once the remaining rotation becomes
            sufficiently small:
          </p>

          <BlockMath
            math={`
              |\omega_i|
              \le
              0.005\;\mathrm{rad/s}
              \quad\Rightarrow\quad
              u_{KR,i}=0.
            `}
          />

          <p>
            Unlike Stabilize mode, Kill Rotation does not contain an absolute
            attitude-restoration term. A stationary spacecraft therefore produces
            zero command even if its orientation differs from an earlier attitude.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>5. Stabilize Control Law</h2>

          <p>
            Stabilize combines quaternion attitude-error feedback with direct
            angular-rate damping. The current control law is
          </p>

          <BlockMath
            math={`
              \mathbf{u}_{S}
              =
              -\mathbf{K}_{P}
              \odot
              \mathbf{e}_q
              -
              \mathbf{K}_{D}
              \odot
              \boldsymbol{\omega}
            `}
          />

          <p>
            The proportional term drives the spacecraft toward the captured
            reference orientation, while the derivative term removes rotational
            kinetic motion and provides damping around the target state.
          </p>

          <p>
            The resulting equilibrium objective is therefore
          </p>

          <BlockMath
            math={`
              q_{current}
              \rightarrow
              q_{target},
              \qquad
              \boldsymbol{\omega}
              \rightarrow
              \mathbf{0}.
            `}
          />
        </section>

        <hr />

        <section className="mathSection">
          <h2>6. Attitude Error Angle</h2>

          <p>
            For evaluation and switching logic, the quaternion error is converted
            into a single physically interpretable angular deviation. After
            shortest-path sign handling, the total attitude error angle is
          </p>

          <BlockMath
            math={`
              \theta_e
              =
              2\arccos
              \left(
              \operatorname{clamp}
              \left(
              q_{e,w},
              -1,
              1
              \right)
              \right).
            `}
          />

          <p>
            The clamping operation protects the inverse cosine against small
            floating-point excursions outside the mathematically valid interval.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>7. Hysteresis for Discrete RCS Actuation</h2>

          <p>
            The current RCS actuation model is binary. A non-zero rotational
            command can therefore result in full thruster activation even when
            the continuous-valued controller output is very small. Initial
            attitude-hold tests showed that a single deadband leads to repeated
            switching around the target state.
          </p>

          <p>
            SDF therefore applies a two-threshold hysteresis to the Stabilize
            correction state.
          </p>

          <h3>Correction OFF condition</h3>

          <BlockMath
            math={`
              \theta_e < 0.5^{\circ}
              \quad\land\quad
              \lVert\boldsymbol{\omega}\rVert_{\infty}
              < 0.005\;\mathrm{rad/s}
            `}
          />

          <h3>Correction ON condition</h3>

          <BlockMath
            math={`
              \theta_e > 1.0^{\circ}
              \quad\lor\quad
              \lVert\boldsymbol{\omega}\rVert_{\infty}
              > 0.010\;\mathrm{rad/s}
            `}
          />

          <p>
            Between these inner and outer thresholds, the previous correction
            state is retained. The resulting Schmitt-trigger-like behavior reduces
            rapid RCS chatter while preserving a bounded attitude-hold region.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>8. Model Variables and Parameters</h2>

          <table>
            <thead>
              <tr>
                <th>Symbol</th>
                <th>Description</th>
                <th>Unit</th>
                <th>Frame / Domain</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><InlineMath math={'q_{target}'} /></td>
                <td>Captured target attitude quaternion</td>
                <td>–</td>
                <td>Attitude representation</td>
              </tr>
              <tr>
                <td><InlineMath math={'q_{current}'} /></td>
                <td>Current spacecraft attitude quaternion</td>
                <td>–</td>
                <td>Attitude representation</td>
              </tr>
              <tr>
                <td><InlineMath math={'q_e'} /></td>
                <td>Quaternion attitude error</td>
                <td>–</td>
                <td>Relative attitude</td>
              </tr>
              <tr>
                <td><InlineMath math={'\mathbf{e}_q'} /></td>
                <td>Vector part of the quaternion attitude error</td>
                <td>–</td>
                <td>3-axis control error</td>
              </tr>
              <tr>
                <td><InlineMath math={'\boldsymbol{\omega}'} /></td>
                <td>Spacecraft body angular velocity</td>
                <td>rad/s</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\mathbf{K}_P'} /></td>
                <td>Attitude-error proportional gain vector</td>
                <td>–</td>
                <td>Controller parameter</td>
              </tr>
              <tr>
                <td><InlineMath math={'\mathbf{K}_D'} /></td>
                <td>Angular-rate damping gain vector</td>
                <td>–</td>
                <td>Controller parameter</td>
              </tr>
              <tr>
                <td><InlineMath math={'\theta_e'} /></td>
                <td>Total quaternion attitude error angle</td>
                <td>rad / deg</td>
                <td>Scalar error metric</td>
              </tr>
              <tr>
                <td><InlineMath math={'\mathbf{u}_S'} /></td>
                <td>Stabilize rotational control command</td>
                <td>–</td>
                <td>SBF control axes</td>
              </tr>
            </tbody>
          </table>
        </section>

        <hr />

        <section className="mathSection">
          <h2>9. Assumptions and Simplifications</h2>

          <ul>
            <li>The attitude quaternion is assumed to remain normalized within numerical tolerance.</li>
            <li>The target attitude remains fixed for the complete duration of one Stabilize activation.</li>
            <li>Angular velocity is directly available in the spacecraft body-fixed frame.</li>
            <li>Controller gains are currently constant and axis-wise.</li>
            <li>No integral control term is applied.</li>
            <li>The controller itself does not model actuator delay or thrust-transient dynamics.</li>
            <li>The hysteresis thresholds are currently engineering parameters rather than analytically optimized switching surfaces.</li>
            <li>RCS allocation remains binary in the present SDF Light formulation.</li>
          </ul>
        </section>

        <hr />

        <section className="mathSection">
          <h2>10. Verification Results</h2>

          <p>
            The following figures are generated from exported SDF telemetry and
            illustrate the measured closed-loop behavior of the current
            quaternion attitude controller.
          </p>

          <figure className="mathFigure">
            <img
              className="mathImage"
              src="/img/math/attitude-stabilize-error.svg"
              alt="Quaternion attitude error during Stabilize mode"
            />
            <figcaption>
              <strong>Figure 1 — Stabilize attitude error.</strong>
              The reference attitude is captured when Stabilize is activated at
              approximately 14.5 s. The initial angular momentum causes a
              substantial transient attitude excursion before the quaternion
              feedback drives the error back toward the target. In the tested
              trajectory, the error first enters the inner 0.5° settling region
              at approximately 27.5 s.
            </figcaption>
          </figure>

          <figure className="mathFigure">
            <img
              className="mathImage"
              src="/img/math/attitude-stabilize-omega.svg"
              alt="Angular-rate envelope during Stabilize mode"
            />
            <figcaption>
              <strong>Figure 2 — Stabilize angular-rate envelope.</strong>
              The maximum absolute body-axis angular velocity is reduced from the
              initial rotational state toward the hysteresis hold region. The
              inner and outer angular-rate thresholds illustrate the separation
              between correction deactivation and re-engagement.
            </figcaption>
          </figure>

          <figure className="mathFigure">
            <img
              className="mathImage"
              src="/img/math/kill-rotation-response.svg"
              alt="Body angular velocity response during Kill Rotation mode"
            />
            <figcaption>
              <strong>Figure 3 — Kill Rotation response.</strong>
              The three body-axis angular velocities are damped toward zero. The
              final residual rates remain within the ±0.005 rad/s deadband used
              by the current Kill Rotation formulation.
            </figcaption>
          </figure>

          <p>
            The telemetry also reveals the limitations of the present binary
            actuator interaction: after the main transient has decayed, short RCS
            correction bursts remain visible as the state moves between the
            hysteresis thresholds. This behavior is bounded and suitable for the
            SDF Light model, while providing a measurable basis for future work on
            pulse modulation, control allocation, and actuator-aware switching
            laws.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>11. Validity and Limitations</h2>

          <p>
            The current formulation provides a compact quaternion-based
            attitude-control model that is suitable for closed-loop 6DoF
            simulation with discrete RCS actuation. It correctly distinguishes
            between pure angular-rate damping and absolute attitude hold, avoids
            Euler-angle singularities, and produces bounded attitude regulation in
            the tested multi-axis cases.
          </p>

          <p>
            The controller should not yet be interpreted as an optimized
            spacecraft attitude-control law. In particular, the continuous PD
            output is coupled to a binary thruster system, while the hysteresis
            limits are fixed engineering values. Future extensions may therefore
            formulate the control problem directly in rotational phase space and
            include minimum-impulse-bit behavior, pulse modulation, actuator
            constraints, and improved control allocation.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>12. References</h2>

          <ul>
            <li>
              Wertz, J. R. (Ed.), <em>Spacecraft Attitude Determination and Control</em>,
              D. Reidel Publishing Company, 1978.
            </li>
            <li>
              Wie, B., <em>Space Vehicle Dynamics and Control</em>, 2nd ed.,
              AIAA Education Series, 2008.
            </li>
            <li>
              Schaub, H. and Junkins, J. L., <em>Analytical Mechanics of Space Systems</em>,
              AIAA Education Series.
            </li>
          </ul>
        </section>

      </main>
    </Layout>
  );
}
