import React from 'react';
import Layout from '@theme/Layout';
import '../../css/mathematics.css';
import { BlockMath, InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css';

export default function RCSControlAllocation() {
  return (
    <Layout
      title="SDF – RCS Control Allocation"
      description="Mathematical formulation of translational and rotational RCS thruster allocation in the Spaceflight Dynamics Framework"
    >
      <main className="mathContainer">

        <h1>RCS Control Allocation</h1>

        <section className="mathSection">
          <h2>1. Model Overview</h2>

          <p>
            The Reaction Control System (RCS) control allocator converts a
            requested spacecraft control command into firing commands for the
            individual RCS thrusters configured on the spacecraft.
          </p>

          <p>
            The allocation problem is distinct from the individual RCS actuator
            model. The actuator model describes how a selected thruster responds
            dynamically once commanded, while the control allocator determines
            which thrusters are compatible with the requested translational or
            rotational motion.
          </p>

          <p>
            SDF currently distinguishes between two allocation paths:
          </p>

          <ul>
            <li>
              <strong>Translational allocation</strong> based on the configured
              thrust-force direction of each thruster.
            </li>
            <li>
              <strong>Rotational allocation</strong> based on the torque direction
              generated by the thruster geometry relative to the current spacecraft
              center of mass.
            </li>
          </ul>

          <p>
            The rotational allocation is intentionally geometry-based. No fixed
            association such as “engine 7 produces positive roll” is required.
            Instead, the allocator evaluates the moment that each configured
            thruster can generate from its mounting position and thrust direction.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>2. Physical / Mathematical Foundation</h2>

          <p>
            Translational control is governed by the direction of the force
            generated by an RCS thruster. A thruster with normalized thrust
            direction <InlineMath math={'\\hat{\\mathbf{d}}_i'} /> produces a
            force vector
          </p>

          <BlockMath
            math={`
              \\mathbf{F}_i
              =
              F_i \\hat{\\mathbf{d}}_i
            `}
          />

          <p>
            Rotational control additionally depends on the point at which the
            force acts. A force whose line of action does not pass through the
            spacecraft center of mass generates a torque according to the moment
            equation
          </p>

          <BlockMath
            math={`
              \\boldsymbol{\\tau}_i
              =
              \\mathbf{r}_i
              \\times
              \\mathbf{F}_i
            `}
          />

          <p>
            where the lever-arm vector is defined from the current center of mass
            to the thruster mounting position:
          </p>

          <BlockMath
            math={`
              \\mathbf{r}_i
              =
              \\mathbf{r}_{thr,i}
              -
              \\mathbf{r}_{CoM}
            `}
          />

          <p>
            This relation forms the physical basis for the rotational RCS
            allocation implemented in SDF.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>3. Derivation</h2>

          <h3>Translational Allocation</h3>

          <p>
            The translational command is represented by a body-frame command
            vector
          </p>

          <BlockMath
            math={`
              \\mathbf{u}_T
              =
              \\begin{bmatrix}
              u_x \\\\
              u_y \\\\
              u_z
              \\end{bmatrix}
            `}
          />

          <p>
            where the sign of each component defines the requested force
            direction along the spacecraft body-fixed axes. For a binary RCS
            actuator, thruster <InlineMath math={'i'} /> is selected when at least
            one non-zero command component has the same sign as the corresponding
            component of the thruster direction vector.
          </p>

          <p>
            Conceptually, the allocation therefore follows
          </p>

          <BlockMath
            math={`
              \\mathbf{u}_T
              \\longrightarrow
              \\hat{\\mathbf{d}}_i
              \\longrightarrow
              c_i \\in \\{0,1\\}
            `}
          />

          <h3>Rotational Allocation</h3>

          <p>
            The rotational command is represented by
          </p>

          <BlockMath
            math={`
              \\mathbf{u}_R
              =
              \\begin{bmatrix}
              u_{roll} \\\\
              u_{pitch} \\\\
              u_{yaw}
              \\end{bmatrix}
            `}
          />

          <p>
            In the spacecraft body-fixed frame, roll, pitch, and yaw correspond
            to the x-, y-, and z-components of the requested torque direction.
          </p>

          <p>
            Because only the direction of the generated torque is required for
            the current binary allocator, the thrust magnitude can be omitted
            from the directional test. Using the normalized thrust direction,
            the generated torque direction is therefore proportional to
          </p>

          <BlockMath
            math={`
              \\boldsymbol{\\tau}_{dir,i}
              =
              \\left(
              \\mathbf{r}_{thr,i}
              -
              \\mathbf{r}_{CoM}
              \\right)
              \\times
              \\hat{\\mathbf{d}}_i
            `}
          />

          <p>
            Thruster <InlineMath math={'i'} /> is selected when the sign of an
            available torque component matches the sign of the requested
            rotational command component. The allocator therefore evaluates the
            actual spacecraft geometry rather than relying on engine names or
            hard-coded roll, pitch, and yaw assignments.
          </p>

          <p>
            The conceptual chain is
          </p>

          <BlockMath
            math={`
              \\mathbf{u}_R
              \\longrightarrow
              \\left(
              \\mathbf{r}_{thr,i}-\\mathbf{r}_{CoM}
              \\right)
              \\times
              \\hat{\\mathbf{d}}_i
              \\longrightarrow
              c_i \\in \\{0,1\\}
            `}
          />
        </section>

        <hr />

        <section className="mathSection">
          <h2>4. Model Variables and Parameters</h2>

          <table>
            <thead>
              <tr>
                <th>Symbol</th>
                <th>Description</th>
                <th>Unit</th>
                <th>Frame</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><InlineMath math={'\\mathbf{u}_T'} /></td>
                <td>Requested translational RCS command</td>
                <td>–</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\mathbf{u}_R'} /></td>
                <td>Requested rotational RCS command</td>
                <td>–</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\hat{\\mathbf{d}}_i'} /></td>
                <td>Normalized thrust direction of thruster i</td>
                <td>–</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\mathbf{r}_{thr,i}'} /></td>
                <td>Thruster mounting position relative to the SBF origin</td>
                <td>m</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\mathbf{r}_{CoM}'} /></td>
                <td>Current spacecraft center-of-mass position</td>
                <td>m</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\mathbf{r}_i'} /></td>
                <td>Lever arm from center of mass to thruster i</td>
                <td>m</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\mathbf{F}_i'} /></td>
                <td>Thrust force generated by thruster i</td>
                <td>N</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'\\boldsymbol{\\tau}_i'} /></td>
                <td>Torque generated by thruster i</td>
                <td>N·m</td>
                <td>SBF</td>
              </tr>
              <tr>
                <td><InlineMath math={'c_i'} /></td>
                <td>Binary allocation command for thruster i</td>
                <td>–</td>
                <td>–</td>
              </tr>
            </tbody>
          </table>
        </section>

        <hr />

        <section className="mathSection">
          <h2>5. Governing Equations</h2>

          <h3>Translational Thruster Compatibility</h3>

          <p>
            For the current binary allocator, a translational thruster is enabled
            when a commanded axis and the corresponding component of its thrust
            direction have matching signs:
          </p>

          <BlockMath
            math={`
              c_i = 1
              \\quad \\text{if} \\quad
              \\exists j \\in \\{x,y,z\\}:
              u_{T,j} \\neq 0
              \\;\\land\\;
              \\operatorname{sgn}(u_{T,j})
              =
              \\operatorname{sgn}(d_{i,j})
            `}
          />

          <h3>Rotational Thruster Compatibility</h3>

          <BlockMath
            math={`
              \\boldsymbol{\\tau}_{dir,i}
              =
              \\left(
              \\mathbf{r}_{thr,i}-\\mathbf{r}_{CoM}
              \\right)
              \\times
              \\hat{\\mathbf{d}}_i
            `}
          />

          <BlockMath
            math={`
              c_i = 1
              \\quad \\text{if} \\quad
              \\exists j \\in \\{x,y,z\\}:
              u_{R,j} \\neq 0
              \\;\\land\\;
              \\operatorname{sgn}(u_{R,j})
              =
              \\operatorname{sgn}(\\tau_{dir,i,j})
            `}
          />

          <p>
            Otherwise, <InlineMath math={'c_i=0'} /> and the thruster is not
            commanded by the allocator.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>6. Coordinate Frames and Conventions</h2>

          <p>
            All vectors used for the current RCS allocation are expressed in the
            spacecraft body-fixed frame (SBF). Thruster mounting positions and
            the spacecraft center of mass therefore share the same reference
            frame and origin definition before the lever arm is formed.
          </p>

          <p>
            The current SDF body-axis convention is interpreted consistently by
            the control input, engine configuration, torque generation, and rigid-
            body rotational dynamics. Positive rotational commands correspond to
            positive torque components about the corresponding SBF axes according
            to the right-hand rule.
          </p>

          <p>
            Thruster direction describes the direction of the force acting on the
            spacecraft. It must not be interpreted as the rotational axis of an
            attitude-control thruster. The rotational effect follows only after
            evaluating the moment arm cross product.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>7. Numerical Solution / Computational Formulation</h2>

          <p>
            The current allocator is evaluated algebraically once per control
            update and does not introduce an additional dynamic state. Each
            candidate thruster is evaluated independently.
          </p>

          <p>
            For translational RCS engines, SDF compares the requested command
            vector with the normalized thrust direction stored in the engine
            configuration.
          </p>

          <p>
            For rotational RCS engines, SDF first computes the current lever arm
            from the configured engine position and current center of mass, then
            evaluates the corresponding torque direction through the cross
            product. The result is reduced to a binary firing command.
          </p>

          <BlockMath
            math={`
              c_i
              \\in
              \\{0,1\\}
            `}
          />

          <p>
            Once allocated, the command is passed to the individual RCS actuator
            model, which applies command delay, rise and decay dynamics, thrust
            generation, and propellant consumption.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>8. Assumptions and Simplifications</h2>

          <ul>
            <li>RCS allocation is currently binary; no continuous thrust weighting is applied.</li>
            <li>Each thruster is evaluated independently against the requested command.</li>
            <li>The configured engine position and thrust direction are assumed to be valid SBF quantities.</li>
            <li>The current center of mass is available in the same body-fixed coordinate system.</li>
            <li>Thruster availability constraints beyond engine activation are not yet optimized globally.</li>
            <li>No plume-interaction or thermal firing constraints are considered by the allocator.</li>
            <li>No minimum-control-effort or propellant-optimal selection criterion is currently applied.</li>
          </ul>
        </section>

        <hr />

        <section className="mathSection">
          <h2>9. Validity and Limitations</h2>

          <p>
            The current formulation provides a geometry-aware and spacecraft-
            independent way to identify thrusters capable of producing a desired
            translational force direction or rotational moment direction. It is
            well suited to the current low-order RCS model and binary control
            architecture.
          </p>

          <p>
            It is not yet a complete six-degree-of-freedom wrench allocator. In
            particular, a translational command is currently allocated from force-
            direction compatibility alone. The allocator does not simultaneously
            require the net torque of all selected translation thrusters to vanish.
            Depending on spacecraft geometry, a nominally translational firing may
            therefore introduce an additional rotational moment.
          </p>

          <p>
            Likewise, the current rotational selection criterion identifies
            thrusters with torque components in the requested direction but does
            not solve a constrained optimization problem for an exact requested
            torque vector, minimum propellant usage, actuator redundancy, or
            simultaneous force cancellation.
          </p>

          <p>
            A future generalized allocator may formulate the complete actuator
            problem in terms of the requested six-dimensional spacecraft wrench
          </p>

          <BlockMath
            math={`
              \\mathbf{w}
              =
              \\begin{bmatrix}
              \\mathbf{F} \\\\
              \\boldsymbol{\\tau}
              \\end{bmatrix}
            `}
          />

          <p>
            and determine a suitable combination of actuator commands subject to
            physical and operational constraints.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>10. Implementation in SDF</h2>

          <p>The current allocation chain is implemented through:</p>

          <ul>
            <li><strong>RCSControlAllocator</strong> – evaluates translational and rotational command compatibility.</li>
            <li><strong>Thrust</strong> – orchestrates propulsion models and applies allocated target commands to the selected engine type.</li>
            <li><strong>IThrustModel</strong> implementations – provide engine identity, type, mounting position, and SBF thrust direction.</li>
            <li><strong>Basic RCS model</strong> – executes the resulting binary actuator command and computes physical thrust and torque.</li>
          </ul>

          <p>
            The rotational allocator uses engine geometry instead of engine-name
            conventions or explicit roll/pitch/yaw assignment metadata. This keeps
            control allocation independent of a specific spacecraft layout.
          </p>
        </section>

        <hr />

        <section className="mathSection">
          <h2>11. Verification</h2>

          <p>
            Formal verification cases for the RCS control allocator are not yet
            published. Planned verification should isolate both allocation paths
            and compare the selected thrusters, resulting net force, and resulting
            net torque against analytically derived reference cases.
          </p>

          <p>Representative planned cases include:</p>

          <ul>
            <li><strong>VER-RCS-ALLOC-001</strong> — Positive and negative translational-axis allocation.</li>
            <li><strong>VER-RCS-ALLOC-002</strong> — Positive and negative roll allocation from configured thruster geometry.</li>
            <li><strong>VER-RCS-ALLOC-003</strong> — Positive and negative pitch allocation from configured thruster geometry.</li>
            <li><strong>VER-RCS-ALLOC-004</strong> — Positive and negative yaw allocation from configured thruster geometry.</li>
            <li><strong>VER-RCS-ALLOC-005</strong> — Center-of-mass offset sensitivity.</li>
            <li><strong>VER-RCS-ALLOC-006</strong> — Detection of unintended torque during nominal translation.</li>
          </ul>
        </section>

        <hr />

        <section className="mathSection">
          <h2>12. References</h2>

          <ul>
            <li>
              Wertz, J. R. (Ed.), <em>Spacecraft Attitude Determination and Control</em>,
              D. Reidel Publishing Company, 1978.
            </li>
            <li>
              Wie, B., <em>Space Vehicle Dynamics and Control</em>, 2nd ed.,
              AIAA Education Series, 2008.
            </li>
            <li>
              Schaub, H. and Junkins, J. L., <em>Analytical Mechanics of Space Systems</em>,
              AIAA Education Series.
            </li>
          </ul>
        </section>

      </main>
    </Layout>
  );
}
